[package]
name = "exicmd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
log = "0.4.22"
thiserror = "1.0.63"
exi = { path = "../"}
env_logger = "0.11.5"
quick-xml = "0.36.1"
